### ISSUE TITLE
Highlighting of UI elements

### ISSUE THREAD

**Issue by eobet** [Eneskp3441/Shaker#2]
I'm a bit puzzled what function the highlights of certain UI elements serve...

1. Here, the Fade In can be clicked and highlighted, but that still doesn't make that field accept numeric keyboard entry, for example.
![image](https://github.com/user-attachments/assets/5dc57f57-92be-49e1-a5d0-079d38173ab4)

2. Here, the array position button has a blue outline (which I haven't seen any other Godot UI element use so far), but the Scale Shake headline is what was last clicked (and btw, that highlight still did not cause the array type settings to expand).
![image](https://github.com/user-attachments/assets/506fb49e-e8f9-4f4e-8485-38233e9ce8d6)

These are nitpicks and overall in principle it's a really nice UI, but I must admit that I can't tell what is (or even can) be collapsed and where to click to expand is a bit confusing...

**Comment by Eneskp3441** [comment]
Problem 1 may be caused by input of a different type, I will review, but the button in problem 2 is for moving, not expanding

**Comment by eobet** [comment]
> Problem 1 may be caused by input of a different type, I will review, but the button in problem 2 is for moving, not expanding

I know it is, but that doesn't explain why it still has a blue border even after I've clicked to highlight an entirely different UI element. :)

**Comment by Eneskp3441** [comment]
Oh, I apologize for misunderstanding the question. Thank you for your feedback. I'll look into this issue as soon as possible!

**Comment by Eneskp3441** [comment]
Hi! I am looking at the first problem but I can't understand the problem, I can enter values from the keyboard by double clicking, am I missing something?
![Godot_v4 2 2-stable_win64_4gsiqpgTi7](https://github.com/user-attachments/assets/5920ab17-3733-48fe-a7dc-0df86be925e3)

**Comment by Eneskp3441** [comment]
And if I understand you correctly, the 2nd problem does not seem to be caused by me because it is present throughout the engine, for example Polygon2D->Data

![Godot_v4 2 2-stable_win64_IekGxKlU4j](https://github.com/user-attachments/assets/7be28fb2-b4f4-4583-83d4-e903d8eaf1d1)

**Comment by eobet** [comment]
Regarding the first issue, you are clicking on the input field, whereas I was clicking on the text. My issue is that the text should not get a highlight unless it accepts input or actually performs an action.

However, judging by your demonstration of the second point, maybe this is a core engine issue as well? I'll report it in Godot main instead.

(Wonder if the inability to reset the value to 0 is also a core engine issue then?)

**Comment by Eneskp3441** [comment]
To be honest, I'm not changing anything related to the UI. I'm just using @export variables, so the parts you're curious about are not things I can modify. Regarding the last thing you mentioned, I could only find this: https://github.com/godotengine/godot/issues/22079
