### ISSUE TITLE
Plugin doesn't load in 4.3

### ISSUE THREAD

**Issue by extechnica** [Eneskp3441/Shaker#6]
**Describe the bug**
When enabling the plugin in 4.3:

**Unable to load addon script from path: 
'res://addons/Shaker-1.0.5/addons/shaker/src/shaker_plugin.gd'. 
This might be due to a code error in that script.
Disabling the addon at 'res://addons/Shaker-1.0.5/addons/shaker/plugin.cfg' to prevent further errors.**

**To Reproduce**
Using Godot 4.3 Stable, install the latest version [1.0.5], and enable the plugin in Project Settings

**Expected behavior**
Shaker to load

**Comment by Eneskp3441** [comment]
Hello, I just tried it in an empty project on the 4.3 stable version, but I didn't encounter any errors. Could you please provide more details if possible?

**Comment by extechnica** [comment]
I see what's happened - thanks for prompting me to retry it. 
Shaker isn't currently showing in the Godot Asset Lib, so I installed with the github instructions:

- Visit the [Shaker plugin GitHub repository](https://github.com/Eneskp3441/Shaker).
- Navigate to the [Releases](https://github.com/Eneskp3441/Shaker/releases) page.
- Download the latest stable release version.
- _Extract the downloaded files_ into your Godot project's addons folder.

But this will fail - the release is actually just the entire repo - the user needs to actually pull out the Shaker-1.0.5/addons/shaker directory and just copy _that_ into their plugins folder.
