### ISSUE TITLE
Add nodes to ShakerComponent2D programmatically

### ISSUE THREAD

**Issue by LaraSQP** [Eneskp3441/Shaker#7]
First of all, thank you very much for making this plugin and for making it available to all.

I am working with Godot 4.3 and the latest release of Shaker (1.0.5).

The Shaker works as expected when used as shown in the documentation.

However, I am having an issue with runtime-generated nodes. They do not shake. This might be a bug or that I am an imbecile. Bear with me.

The nodes are created programmatically and added to various children of children of the siblings of a ShakerComponent2D object. This might be an issue, I do not know.

As the nodes are created and added to various other nodes, I am using a loop that essentially contains:

```
newNode = n.instantiate()
someOtherNode.add_child( newNode  )
shaker.Targets.append( newNode )
print( shaker.Targets.size() )
```

The console prints 0 over and over, meaning the nodes are not being appended to the target array of the shaker.

Any clues would be appreciated.

Thanks again.

**Comment by Eneskp3441** [comment]
Hello, I just tried it, and I see that it's working without any issues. Is the custom target variable of ShakerComponent2D active? Also, if you enable AutoPlay, it should start automatically when the game begins

**Comment by LaraSQP** [comment]
Thank you for the quick reply.

Yes, `custom targets` is on in the `inspector`.

`Auto play` is not on because it is triggered programmatically via `play_shake()`

Do I understand that you have created nodes programmatically and added them to various children of children (and to `shaker.Targets.append( newNode )` ) and it works for you?

This means that `print( shaker.Targets.size() )` will print the number of nodes added, correct?

If so, do you have a basic test sample code I can look at?

Thanks again.

**Comment by LaraSQP** [comment]
Oddly, when I try to use the `Inspector` directly to add elements to the `Targets` array, the `Assign` button shows everything grayed out.

![image](https://github.com/user-attachments/assets/eaf1d3a4-7c25-45ba-863c-73883b3470f6)

**Comment by LaraSQP** [comment]
Darn, I think the problem is that I am trying to assign nodes that do not inherit from `Node2D`. That would do it. Will check.

**Comment by LaraSQP** [comment]
That was the problem. The nodes did not inherit from `Node2D`. Everything works now and it's great.

Thanks again and apologies. Me be the slowpoke.
